export const ADD_TO_CART = "ADD_TO_CART"

export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM"

export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO"

export const STRIPE_SECRET_KEY = "sk_test_51LBQWjSJvj2OLGD67zEWwjBWcO0tlFKXxVIfpKKMYzvaXhbDFvmmnZNgZEN4plQqmsLcMcDsisSVSXqlAJIyCPKj00rw9vMzPj"

export const STRIPE_API_KEY = "sk_test_51LBQWjSJvj2OLGD67zEWwjBWcO0tlFKXxVIfpKKMYzvaXhbDFvmmnZNgZEN4plQqmsLcMcDsisSVSXqlAJIyCPKj00rw9vMzPj"